"""Export the functions the public project page displays, straight from the source.

The page used to show invented code: functions and constants that existed nowhere in this
repository. This script makes the page's code a generated artifact instead, so it cannot
drift from the implementation and a reader can diff one against the other.

Usage:
    python scripts/export_page_snippets.py            # verify the artifact is current
    python scripts/export_page_snippets.py --write    # regenerate it
"""

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC = PROJECT_ROOT / "src" / "corpus_privacy_intelligence"
ARTIFACT = PROJECT_ROOT / "docs" / "artifacts" / "page_snippets.json"

# Page tab -> (module, function). These are the four panes under "Classification passes".
EXPORTS = {
    "policy": ("validators.py", "policy_classifier"),
    "strict": ("validators.py", "strict_detector"),
    "semantic": ("validators.py", "semantic_score_classifier"),
    "ensemble": ("advanced_validation.py", "weighted_ensemble"),
}


def extract(module: str, name: str) -> str:
    """Return a top-level function verbatim, from its def line to its last indented line."""
    text = (SRC / module).read_text(encoding="utf-8")
    needle = f"def {name}("
    if needle not in text:
        sys.exit(f"{name} not found in {module}")
    lines = text[text.index(needle) :].split("\n")
    out = [lines[0]]
    for line in lines[1:]:
        if line and not line[0].isspace():
            break
        out.append(line)
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out)


def build() -> dict:
    return {
        "_about": (
            "Verbatim source of the functions shown on the public project page. Generated by "
            "scripts/export_page_snippets.py and verified in CI, so the page cannot display "
            "code that does not exist."
        ),
        "snippets": {
            tab: {
                "source": f"src/corpus_privacy_intelligence/{module}",
                "function": name,
                "code": extract(module, name),
            }
            for tab, (module, name) in EXPORTS.items()
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the artifact")
    args = parser.parse_args()

    current = build()
    if args.write:
        ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
        ARTIFACT.write_text(json.dumps(current, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"wrote {ARTIFACT.relative_to(PROJECT_ROOT)} ({len(current['snippets'])} snippets)")
        return

    if not ARTIFACT.exists():
        sys.exit(f"missing {ARTIFACT}. Run: python scripts/export_page_snippets.py --write")
    stored = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    stale = [
        tab
        for tab, entry in current["snippets"].items()
        if stored.get("snippets", {}).get(tab, {}).get("code") != entry["code"]
    ]
    if stale:
        print("page snippets are stale for: " + ", ".join(sorted(stale)))
        sys.exit("Run: python scripts/export_page_snippets.py --write")
    print(f"page snippets match the source ({len(current['snippets'])} functions)")


if __name__ == "__main__":
    main()
